### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Jendker** [rimar/wifi-location-changer#13]
After starting the instalation with the 'install' script and after input of the password I got the following error:

/Users/<My user>/Library/LaunchAgents/LocationChanger.plist: Could not find specified service

What can be the cause? I am using OSX High Sierra 10.13.4.

**Comment by rimar** [comment]
Did you try to run the commands in ./install manually? Does it work? What's the output?

**Comment by Jendker** [comment]
I was getting the error during the execution of ./install script:
launchctl unload ~/Library/LaunchAgents/LocationChanger.plist

I don't know if that's important to find the way around this, everything is working fine apart from this error. Thanks for sharing your work!
