### ISSUE TITLE
Change to "automatic" unspecified wifi SSID

### ISSUE THREAD

**Issue by niccolobusato** [rimar/wifi-location-changer#18]
Set as automatic all wifi networks not "known" and not specified in the locationchanger

**Comment by TechOverflow** [comment]
Yep, defaulting to Automatic would be nice.

**Comment by jbell1995** [comment]
Is this at all possible?

**Comment by YannBrrd** [comment]
Done already, AFAIK.

**Comment by putchi** [comment]
it is now defaulting to 
`Location_Automatic="Automatic"`
