### ISSUE TITLE
Make clik on notification close the notification instead of opening Script editor

### ISSUE THREAD

**Issue by YannBrrd** [rimar/wifi-location-changer#19]
Hi,

At the moment, when I click on notif, it opens Script Editor. Would be nice if it does nothing on closes the notif.

Thx.

**Comment by putchi** [comment]
Hi @YannBrrd, You can try and use the Growl app for system notifications and define what to do on click actions. with aplescript notifications (default MacOS system notifications) you cannot change the on click action as it will try to open the script editor. 

from the docs:
display notification

Posts a notification using the Notification Center, containing a title, subtitle, and explanation, and optionally playing a sound.

Syntax
display notification – text, required
with title – text, optional
subtitle – text, optional
sound name – text, optional

[reference](https://developer.apple.com/library/archive/documentation/AppleScript/Conceptual/AppleScriptLangGuide/reference/ASLR_cmds.html#//apple_ref/doc/uid/TP40000983-CH216-SW224)
