### ISSUE TITLE
Support for macOS Monterey (12.0)

### ISSUE THREAD

**Issue by ZV00** [rimar/wifi-location-changer#27]
Good morning! 

Just reaching out to see if there's any plan to fully support macOS Monterey potentially on the horizon? I'd love to be able to use this tool actively on Monterey. 

Thanks!

**Comment by Gasman2014** [comment]
I think I have it working by adding the watch paths recommended elsewhere 

```
<key>WatchPaths</key>
    <array>
        <string>/Library/Preferences/SystemConfiguration/com.apple.airport.preferences.plist</string>
        <string>/Library/Preferences/SystemConfiguration/com.apple.wifi.message-tracer.plist</string>
        <string>/Library/Preferences/com.apple.wifi.known-networks.plist</string>
    </array>
```
and starting the service with 

`launchctl enable gui/$UID/LocationChanger`

**Comment by putchi** [comment]
Hi @Gasman2014 the same worked for me as well. I did that change a few months ago with the release of Monterey.

**Comment by ZV00** [comment]
I will readily admit I’m not sure how to go about making this happen. Are you able to provide an instructions by any chance?

Thanks
