### ISSUE TITLE
Detect hostname and MAC address of router

### ISSUE THREAD

**Issue by alexreg** [rimar/wifi-location-changer#35]
Thanks for publishing this nice little utility. I was thinking it would be a useful new feature to be able to detect the hostname and MAC address of the current router, and use this this to switch location. SSID is good enough in many cases, of course, but naturally not all.

**Comment by alexreg** [comment]
Note, this information is available via the command-line with `arp -a`, though perhaps there's an easier or more programmatic way to get it.

**Comment by putchi** [comment]
Hi @alexreg  if you have the time please free to contribute with a PR and we will review :)

**Comment by alexreg** [comment]
@putchi Thanks, I'll see if I can work something out.
