### ISSUE TITLE
support for sonoma 14

### ISSUE THREAD

**Issue by SealinGp** [rimar/wifi-location-changer#45]
Apple M1 Pro
macOS Sonoma 14.4 Beta
<img width="1394" alt="image" src="https://github.com/rimar/wifi-location-changer/assets/32982627/28ea4d33-e936-4520-ac85-1ffc00729d78">
<img width="507" alt="image" src="https://github.com/rimar/wifi-location-changer/assets/32982627/5494529e-049b-40cf-b598-174a150c41f8">
<img width="585" alt="image" src="https://github.com/rimar/wifi-location-changer/assets/32982627/f139b2b7-b4c8-4c64-bbe5-3eccd37cbe11">

conf in sonoma
```bash
cat /usr/local/bin/locationchanger.conf
# This is a sample file for creating text file "locationchanger.conf" which associates location names with wifi names.
#
# Below, enter two pieces of text: location and wifi, separated by space(s)
# If the wifi name contains space(s), make sure to put quotes around that wifi name; location may NOT have any spaces or odd characters.
# Any line with a pound sign in front will be ignored as a comment. Blank lines are also ignored.
#
#
# LOCATION  WIFI
#
# For example:
# Home myHomeWifiSSID
# Work "my Work Wifi"
TPARTS-GFW "TPARTS-GFW"

**Comment by SealinGp** [comment]
I read 'MacOS Ventura fallback to Automatic location issue', it didn't help

after change /usr/local/var/log permission
```bash
chown -R local_user:wheel /usr/local/var/log
```
i can see the log below
```bash
tail -f /usr/local/var/log/locationchanger.log
Mon Apr 8 13:04:11 CST 2024 New SSID found:
Mon Apr 8 13:04:22 CST 2024 New SSID found:
Mon Apr 8 13:04:32 CST 2024 New SSID found:
Mon Apr 8 13:04:43 CST 2024 New SSID found:

**Comment by samgurung** [comment]
running install.sh in sonoma causes this error 
`Unload failed: 5: Input/output error
Try running `launchctl bootout` as root for richer errors.
Bootstrap failed: 5: Input/output error`

Any ideas how to resolve?

**Comment by devopsbrett** [comment]
> I read 'MacOS Ventura fallback to Automatic location issue', it didn't help
> 
> after change /usr/local/var/log permission
> 
> ```shell
> chown -R local_user:wheel /usr/local/var/log
> ```
> 
> i can see the log below
> 
> ```shell
> tail -f /usr/local/var/log/locationchanger.log
> Mon Apr 8 13:04:11 CST 2024 New SSID found:
> Mon Apr 8 13:04:22 CST 2024 New SSID found:
> Mon Apr 8 13:04:32 CST 2024 New SSID found:
> Mon Apr 8 13:04:43 CST 2024 New SSID found:
> ```

Hi, the reason for the blank values for SSID is due to `/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport` command now being deprecated and not listing your current wifi network. It suggests to use wdutil but this requires sudo. I was able to get it working by changing line 26 in `locationchanger` to 

```
SSID=`networksetup -getairportnetwork en0 | awk -F ': ' '{print $2}'`
```

This doesn't require sudo and has fixed the issue for me

**Comment by SealinGp** [comment]
> 26

i forked this repo and this way works for my situation. so i close the issue.

**Comment by 01awolf** [comment]
Hi
Same issue reappears with Sequoia 15.
Any idea how to solve it ?
Thank you
