### ISSUE TITLE
Default settings

### ISSUE THREAD

**Issue by ImanMh** [rimar/wifi-location-changer#8]
If you connect to a WiFi that has for example a manual IP setting and then try to connect to a WiFi that you don't have any settings for, wifi-location-changer wouldn't change the previous settings which is totally expected but may not be what you expect. 
I wish I could create a default location name and when there is no configurations available for a WiFi, wifi-location-changer would use that default settings.

**Comment by rimar** [comment]
IIRC you can achieve that by defining location called: Automatic

**Comment by ImanMh** [comment]
Thanks :)
